#!/usr/bin/python
import pexpect
import sys
import re

router_name="192.168.1.216"
router_user="admin"
router_pass="Hcu56!"
routes=[]
clearRoute=[]
scriptName = sys.argv[0]

#check to make sure we have a config file specified
if len(sys.argv) < 3 :
	print('USAGE: %s [configFile] [farmington/clearfield]' % (scriptName))
	print('EXAMPLE: %s farmington-confg farmington' % (scriptName))
	exit(1)

configFile = sys.argv[1]
routeProfile = sys.argv[2].lower()

#Make sure a valid branch is passed in
if routeProfile != 'farmington' and routeProfile != 'clearfield':
	print ('Not a valid branch')
	exit(1)

#Read configFile into config line by line
with open(configFile) as file:
	config = file.readlines()

#Extract routes from the config file
for i in range(len(config)):
        routeSearch = re.search( r'(ip route.*)' ,config[i])

        #strip () and , from the results and append to routes list
        if hasattr(routeSearch,'groups'):
                newRoute = re.sub('[(),\']','',str(routeSearch.groups()))
                routes.append(newRoute)


#Change routes for clearfield routing
if routeProfile == 'clearfield':
	for i in range(len(routes)):
		routes[i] = re.sub(r'(192\.168\.1\.3$)','192.168.3.3',routes[i])
		routes[i] = re.sub(r'(192\.168\.1\.4$)','192.168.3.4',routes[i])
		routes[i] = re.sub(r'(192\.168\.1\.223$)','192.168.3.223',routes[i])
		routes[i] = re.sub(r'(192\.168\.1\.217$)','192.168.3.217',routes[i])

#Attempt to connect to the router
try:
	child = pexpect.spawn('ssh %s@%s -1' % (router_user, router_name))
#	child.logfile = sys.stdout
	child.timeout = 5
	child.expect('password:')
	
except pexpect.TIMEOUT:
	print ("Did not recieve login prompt")
	exit(1)


#Login to router
child.sendline(router_pass)
child.expect('>')
child.sendline('en')
child.expect('Password:')
child.sendline(router_pass)
child.expect('#')
child.sendline('conf t')
child.expect('#')

#Send Routes
for i in range(len(routes)):
	child.sendline( routes[i])
	child.expect('#')

#Log out of router
child.sendline('exit')
child.expect('#')
child.sendline('exit')

#Print routes that were added
print ("The following routes were added:\n")
for i in range (len(routes)):
	print routes[i]
print ('\n')
#End script
exit(0)

